name: Build ApproxAI on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install -r requirements.txt pyinstaller
      - name: Build exe
        run: |
          .\venv\Scripts\activate
          pyinstaller --onefile --windowed --name ApproxAI ApproxAI.py
      - name: Upload Windows exe
        uses: actions/upload-artifact@v2
        with:
          name: ApproxAI-exe
          path: dist/ApproxAI.exe
